/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as DocumentsIdTypeRouteImport } from './routes/documents.$id.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdTypeRoute = DocumentsIdTypeRouteImport.update({
  id: '/documents/$id/$type',
  path: '/documents/$id/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/patients/$id': typeof PatientsIdRoute
  '/documents/$id/$type': typeof DocumentsIdTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/patients/$id': typeof PatientsIdRoute
  '/documents/$id/$type': typeof DocumentsIdTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/patients/$id': typeof PatientsIdRoute
  '/documents/$id/$type': typeof DocumentsIdTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/patients/$id' | '/documents/$id/$type'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/patients/$id' | '/documents/$id/$type'
  id: '__root__' | '/' | '/about' | '/patients/$id' | '/documents/$id/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PatientsIdRoute: typeof PatientsIdRoute
  DocumentsIdTypeRoute: typeof DocumentsIdTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id/$type': {
      id: '/documents/$id/$type'
      path: '/documents/$id/$type'
      fullPath: '/documents/$id/$type'
      preLoaderRoute: typeof DocumentsIdTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PatientsIdRoute: PatientsIdRoute,
  DocumentsIdTypeRoute: DocumentsIdTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
